### ISSUE TITLE
Upload error

### ISSUE THREAD

**Issue by coldnebraskablue** [XCentium/XBlog#2]
Hi, 
We're just trying to upload a Wordpress export into xBlog but keep getting the following error in the Sitecore logs:

_84 15:28:31 ERROR Failed to read xml: String was not recognized as a valid DateTime because the day of week was incorrect._

Now, obviously this appears to be referring to a date / time element somewhere in the file, but is there anything we can do to try and pin this down? As best I can see, there is no other information. 

Thanks,   Paul

**Comment by zmalmquist** [comment]
Hi Paul,

I think some XML clean up could help you out.  First you could pull out of the XML any comments you might have.  Since XBlog currently does not have comments we don't support the import of them.  Secondly look to the "pubDate" node.  That is the field we pull in for import, so likely your culprit is there if not with comments.

Beyond that I have had luck with doing partial imports.  Leave one to five of the top posts and remove the rest.  If it imports, you go on to the larger groups until you find an error.  You can always delete blog tests later on from the content tree.

Let me know what you find out.  Maybe we can work that into some checks to improve the importer.

thanks,

Zac

**Comment by coldnebraskablue** [comment]
Hi Zac, thanks for getting back to us. 

Yeah we've been doing the partial imports but its slow and laborious work. Have removed the wordpress comments. 

Have found a few of the following:
_  <pubDate>Mon, 30 Nov -0001 00:00:00 +0000</pubDate>_
Changing the date part to something sensible didn't seem to work (surprisingly), but then changing the time to something other than midnight _did_ seem to help... 

Also had a few of these that I changed to something sensible, don't know if they would cause a problem or not:
<wp:post_date_gmt>0000-00-00 00:00:00</wp:post_date_gmt>

But it's not clear cut - i've only had one successful import on a very small file where the original publishing dates of the posts has been respected inside of the bucket. Other "successful" imports have resulted in everything appearing under one date, todays. 

There are also entries like this in the log file:
3380 16:19:23 ERROR Cannot create entry for: This is some test text. End of string expected at position 31.

Different items, but always "position 31"

Thanks,    Paul

**Comment by zmalmquist** [comment]
I assume you have downloaded source code?  Take a look at:  XBlogHelper.Models.Import.WPPost.GetPost().

`if (postXml.Element("pubDate") != null)
                PublishDate = DateTime.Parse(postXml.Element("pubDate").Value);`

I suspect better error checking on this would resolve your problem.   DateTime.TryParse is probably what is needed.

thanks,

Zac
